package entity

import java.sql.Timestamp


case class StkOrder(
                     TRD_DATE: Int,
                    REC_SN: Long,
                    ORDER_TIME: Timestamp,
                    ORDER_SN: Long,
                    ORDER_BSN: Long,
                    ORDER_ID: String,
                    RAW_ORDER_ID: String,
                    ORDER_TYPE: String,
                    ORDER_STATUS: String,
                    SUBSYS: Int,
                    SUBSYS_SN: String,
                    INT_ORG: Int,
                    CUST_CODE: String,
                    CUST_NAME: String,
                    CUST_TYPE: String,
                    CUST_CLS: String,
                    CUACCT_CODE: String,
                    CUACCT_ATTR: String,
                    CUACCT_CLS: String,
                    CUACCT_LVL: String,
                    CUACCT_GRP: String,
                    CUACCT_DMF: String,
                    BANK_CODE: Long,
                    MARKET: String,
                    BOARD: String,
                    STKPBU: String,
                    FIRMID: String,
                    TRDACCT: String,
                    TRDACCT_EXID: String,
                    TRDACCT_TYPE: String,
                    TRDACCT_EXCLS: String,
                    TRD_ID: String,
                    STK_BIZ_EX: String,
                    STK_CODE: String,
                    STK_NAME: String,
                    STK_CLS: String,
                    CURRENCY: String,
                    BOND_INT: Int,
                    ORDER_PRICE: BigDecimal,
                    ORDER_QTY: Long,
                    ORDER_AMT: Long,
                    ORDER_FRZ_AMT: Long,
                    ORDER_UFZ_AMT: Long,
                    WITHDRAWN_QTY: Long,
                    MATCHED_QTY: Long,
                    MATCHED_AMT: Long,
                    RLT_SETT_AMT: Long,
                    IS_WITHDRAW: String,
                    IS_WITHDRAWN: String,
                    OP_USER: String,
                    OP_ROLE: String,
                    OP_NAME: String,
                    OP_ORG: Long,
                    OP_SITE: String,
                    CHANNEL: String,
                    UPDATE_TIME: Timestamp,
                    MEETING_CODE: String,
                    VOTE_ID: String,
                    ORDER_DETAIL_FLAG: String,
                    MATCH_TIME: Int,
                    RPTPBU: String) extends Serializable {

}
